# application-local.properties
# Este archivo NO se sube a Git (agrega a .gitignore si deseas)
# Sobreescribe los valores de application.properties para tu entorno local

spring.datasource.username=postgres
spring.datasource.password=admin123
spring.mail.username=dredge3216@gmail.com
spring.mail.password=pxbz yrat txwa urzp
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.security=TRACE

# Cloudinary
cloudinary.cloud_name=kdjlvo1a
cloudinary.api_key=362896654353711
cloudinary.api_secret=n6e2omMUZnXhIX8ETE1cdTgYDqc
